services:
  # For local development, we only run Redis and RabbitMQ in Docker
  # The app runs locally with npm run start:dev for hot reloading
  
  redis:
    image: redis:7-alpine
    container_name: pulse-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - pulse-dev-network
    # No password for local development
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pulse-rabbitmq-dev
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq
    networks:
      - pulse-dev-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  pulse-dev-network:
    driver: bridge

volumes:
  redis-dev-data:
  rabbitmq-dev-data: