version: '3.8'

services:
  app:
    image: flashapp/whatsapp-service:test
    container_name: flash-whatsapp-service-test
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
    depends_on:
      - redis
      - rabbitmq
    networks:
      - flash-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:alpine
    container_name: flash-whatsapp-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-test-data:/data
    networks:
      - flash-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flash-whatsapp-rabbitmq-test
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq-test-data:/var/lib/rabbitmq
    networks:
      - flash-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  flash-network:
    driver: bridge

volumes:
  redis-test-data:
  rabbitmq-test-data: