apiVersion: v1
kind: ConfigMap
metadata:
  name: flash-whatsapp-config
  namespace: flash-production
data:
  flash_api_url: "https://api.flashapp.me/graphql"
  maple_ai_url: "https://api.trymaple.ai/v1"
  logging_level: "info"
  # Add other non-sensitive configuration values here
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flash-whatsapp-config-test
  namespace: flash-test
data:
  flash_api_url: "https://test.api.flashapp.me/graphql"
  maple_ai_url: "https://test-api.trymaple.ai/v1"
  logging_level: "debug"
  # Add other non-sensitive configuration values here