apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-connect
  namespace: flash-production
  labels:
    app: flash-connect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flash-connect
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flash-connect
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: flash-connect
        image: flashapp/flash-connect:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: flash-connect-redis
              key: host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: flash-connect-redis
              key: port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flash-connect-redis
              key: password
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: flash-connect-rabbitmq
              key: url
        - name: FLASH_API_URL
          valueFrom:
            configMapKeyRef:
              name: flash-whatsapp-config
              key: flash_api_url
        - name: FLASH_API_KEY
          valueFrom:
            secretKeyRef:
              name: flash-whatsapp-api
              key: api_key
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: flash-whatsapp-twilio
              key: account_sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: flash-whatsapp-twilio
              key: auth_token
        # Gemini AI doesn't need a URL configuration
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: flash-whatsapp-gemini
              key: api_key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: flash-whatsapp-jwt
              key: secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flash-connect
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: flash-connect
  namespace: flash-production
  labels:
    app: flash-connect
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: flash-connect
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flash-connect
  namespace: flash-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  tls:
  - hosts:
    - whatsapp.flashapp.me
    secretName: whatsapp-flashapp-me-tls
  rules:
  - host: whatsapp.flashapp.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flash-connect
            port:
              number: 80