name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Set up Redis service container
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        # Health check to wait for redis to be ready
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # Set up RabbitMQ service container
      rabbitmq:
        image: rabbitmq:3.9-alpine
        ports:
          - 5672:5672
        # Health check to wait for rabbitmq to be ready
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check TypeScript compilation
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NODE_ENV: test
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: ''
          REDIS_DB: 1
          RABBITMQ_URL: amqp://localhost:5672
          JWT_SECRET: test_jwt_secret_min_32_chars_for_testing_only
          ENCRYPTION_KEY: test_encryption_key_min_32_chars_for_testing
          ENCRYPTION_SALT: test_salt_16char
          HASH_SALT: test_hash_16char
          SESSION_SECRET: test_session_secret_min_32_chars_for_testing
          WEBHOOK_SECRET: test_webhook_secret_min_32_chars_for_testing
          ENABLE_INTRALEDGER_POLLING: false
          ENABLE_WEBSOCKET_NOTIFICATIONS: false
          LOG_LEVEL: error

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --production

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Flash Connect'
          path: '.'
          format: 'HTML'
          args: >
            --suppression ./.github/dependency-check-suppressions.xml
            --failOnCVSS 7
            --enableRetired

      - name: Upload dependency check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}