name: Monitoring & Alerts

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  health-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, production]
    steps:
      - name: Health check - ${{ matrix.environment }}
        id: health_check
        run: |
          URL="${{ matrix.environment == 'production' && 'https://whatsapp.flashapp.me/health' || 'https://test.whatsapp.flashapp.me/health' }}"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
          
          echo "HTTP Status: $STATUS"
          
          if [[ "$STATUS" == "200" ]]; then
            echo "status=healthy" >> $GITHUB_OUTPUT
          else
            echo "status=unhealthy" >> $GITHUB_OUTPUT
          fi

      - name: Send alert on unhealthy status
        if: steps.health_check.outputs.status == 'unhealthy'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C01234ABCDEF'
          slack-message: |
            :red_circle: Flash Connect is DOWN in ${{ matrix.environment }}
            
            Environment: ${{ matrix.environment }}
            Time: ${{ steps.health_check.outputs.time }}
            
            Please investigate immediately!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  performance-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, production]
    steps:
      - name: Performance check - ${{ matrix.environment }}
        id: perf_check
        run: |
          URL="${{ matrix.environment == 'production' && 'https://whatsapp.flashapp.me/health' || 'https://test.whatsapp.flashapp.me/health' }}"
          
          # Run 3 requests and measure time
          TIMES=()
          for i in {1..3}; do
            TIME=$(curl -s -w "%{time_total}\n" -o /dev/null $URL)
            TIMES+=($TIME)
          done
          
          # Calculate average
          SUM=0
          for t in "${TIMES[@]}"; do
            SUM=$(echo "$SUM + $t" | bc)
          done
          AVG=$(echo "scale=3; $SUM / ${#TIMES[@]}" | bc)
          
          echo "Average response time: $AVG seconds"
          
          if (( $(echo "$AVG > 1.0" | bc -l) )); then
            echo "status=slow" >> $GITHUB_OUTPUT
            echo "response_time=$AVG" >> $GITHUB_OUTPUT
          else
            echo "status=normal" >> $GITHUB_OUTPUT
            echo "response_time=$AVG" >> $GITHUB_OUTPUT
          fi

      - name: Send alert on slow performance
        if: steps.perf_check.outputs.status == 'slow'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C01234ABCDEF'
          slack-message: |
            :warning: Flash Connect is running slow in ${{ matrix.environment }}
            
            Environment: ${{ matrix.environment }}
            Response Time: ${{ steps.perf_check.outputs.response_time }} seconds
            Threshold: 1.0 seconds
            
            Please investigate performance issues!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  error-log-check:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Check for error logs - Production
        id: error_check
        run: |
          # Check logs for the last 30 minutes
          THIRTY_MINS_AGO=$(date -u -d '30 minutes ago' +"%Y-%m-%dT%H:%M:%SZ")
          
          # Count errors in logs
          ERROR_COUNT=$(gcloud logging read "resource.type=k8s_container AND resource.labels.namespace_name=flash-production AND resource.labels.container_name=flash-connect AND severity>=ERROR AND timestamp>=\"$THIRTY_MINS_AGO\"" --limit=1000 --format="value(textPayload)" | wc -l)
          
          echo "Error count in the last 30 minutes: $ERROR_COUNT"
          
          if [[ "$ERROR_COUNT" -gt 10 ]]; then
            echo "status=high_errors" >> $GITHUB_OUTPUT
            echo "error_count=$ERROR_COUNT" >> $GITHUB_OUTPUT
          else
            echo "status=normal" >> $GITHUB_OUTPUT
            echo "error_count=$ERROR_COUNT" >> $GITHUB_OUTPUT
          fi

      - name: Send alert on high error count
        if: steps.error_check.outputs.status == 'high_errors'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C01234ABCDEF'
          slack-message: |
            :warning: Flash Connect has a high error rate
            
            Environment: Production
            Error Count: ${{ steps.error_check.outputs.error_count }} in the last 30 minutes
            Threshold: 10 errors
            
            Please check logs for details!
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}